

#define SOUND_ID_ENERGIZE		1
#define SOUND_ID_BEAM			2
#define SOUND_ID_TELEPORT		3
#define SOUND_ID_WARP			4

#define ICON_T3DX				100
#define CURSOR_CROSSHAIR		200

#define MENU_FILE_ID_EXIT		1000

#define MENU_PLAY_ID_ENERGIZE	2000
#define MENU_PLAY_ID_BEAM		2001
#define MENU_PLAY_ID_TELEPORT	2002
#define MENU_PLAY_ID_WARP		2003

#define MENU_HELP_ABOUT			3000
